RO-3780: Extend the schema with CARD annotations
rcsb/py-rcsb_exdb_assets pull request #115
Opened 2023-03-07 01:27 UTC by piehld

[RO-3780](https://rcsbpdb.atlassian.net/browse/RO-3780):
- Add CARD annotations to entity-level annotations dictionaries
- Add 'additional_properties' to entity-level annotation dictionaries
- Fixed `additional_properties` `_item.name` in entity-level features dictionaries

2023-03-07 01:31 UTC, piehld commented
Hey @brindakv, this is for one of my tickets (https://rcsbpdb.atlassian.net/browse/RO-3780). I understand I'll need to regenerate the schema files as well, but before doing that I thought I'd request your review of the source files first.

If you'd like me to generate and push them now as well though, just let me know. 

Thank you!

2023-03-07 01:48 UTC, brindakv commented
> If you'd like me to generate and push them now as well though, just let me know.

@piehld Please do not regenerate the schema yet. I'd like to know the reason behind moving this from features to annotations. I missed that discussion.

2023-03-07 02:40 UTC, valasatava requested changes
Thank you, @piehld for taking time to focus on this! Just one comment about removing existing definitions from schema: the safest way would be to stop populating them with the data at this point and remove them when we move to data API v2: https://rcsbpdb.atlassian.net/browse/RO-3801.

2023-03-07 02:40 UTC, valasatava commented on dictionary_files/extensions/features/rcsb_entity_feature.dic
> -    'CARD_MODEL' 'Comprehensive Antibiotic Resistance Database Detection Model' 'CARD AMR Detection Model' .
At this point we want to stop populating CARD definitions with data. We will remove schema definitions as a part of Data API v2: https://rcsbpdb.atlassian.net/browse/RO-3801

2023-03-07 02:58 UTC, piehld commented on dictionary_files/extensions/features/rcsb_entity_feature.dic
> -    'CARD_MODEL' 'Comprehensive Antibiotic Resistance Database Detection Model' 'CARD AMR Detection Model' .
@valasatava OK sure, that makes sense. I'm working on making the code changes to stop populating the features in another repo, which I'll plan to push this week so we see the effect next week. I'll bring these schema definitions back too until Data API v2.

2023-03-07 13:30 UTC, brindakv requested changes
@piehld Do `_rcsb_entity_annotation.additional_properties_name` and `_rcsb_entity_annotation.additional_properties_values` belong to a nested subcategory?

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    _item.name               '_rcsb_entity_annotation.additional_properties_value'
`_item.name` has to be `_rcsb_entity_annotation.additional_properties_name`

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    _item_examples.case  PARENT_COMP_ID
`_item_examples.case` should be one from the enumeration.

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    _item.name               '_rcsb_entity_annotation.additional_properties_value'
`_item.name` has to be `_rcsb_entity_annotation.additional_properties_values`

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    'CARD' 'Comprehensive Antibiotic Resistance Database Detection' 'CARD' .
Perhaps give a better name for `rcsb_detail_brief`.

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic
> +    _item.name               '_rcsb_polymer_entity_annotation.additional_properties_value'
`_item.name` should be `_rcsb_polymer_entity_annotation.additional_properties_name`.

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic
> +    _item_examples.case  PARENT_COMP_ID
`_item_examples.case` should be one from the enumeration.

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic
> +    _item.name               '_rcsb_polymer_entity_annotation.additional_properties_value'
`_item.name` should be `_rcsb_polymer_entity_annotation.additional_properties_values`.

2023-03-07 13:30 UTC, brindakv commented on dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic
> +    _item_examples.case  globin-like 2.54  300
`_item_examples.case` can be from CARD.

2023-03-07 15:29 UTC, piehld commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    _item.name               '_rcsb_entity_annotation.additional_properties_value'
Good catch, thanks! Should we also fix this for the features dict too then (where I copied these categories from)?

- https://github.com/rcsb/py-rcsb_exdb_assets/blob/development/dictionary_files/extensions/features/rcsb_polymer_entity_feature.dic#L294
- https://github.com/rcsb/py-rcsb_exdb_assets/blob/development/dictionary_files/extensions/features/rcsb_entity_feature.dic#L312

2023-03-07 15:31 UTC, piehld commented on dictionary_files/extensions/annotations/rcsb_entity_annotation.dic
> +    _item.name               '_rcsb_entity_annotation.additional_properties_value'
Another good catch. Should this also be updated in the two other features dicts that I linked to in my other comment?

2023-03-07 15:40 UTC, piehld commented
> @piehld Do `_rcsb_entity_annotation.additional_properties_name` and `_rcsb_entity_annotation.additional_properties_values` belong to a nested subcategory?

Thanks for the review @brindakv. I'll be honest that I don't fully grasp how the subcategory nesting works...I had just copied the two `additional_properties` categories from `rcsb_polymer_entity_features.dic` to add the same in for `annotations`, but could easily have missed something else I needed to do. Would you be able to meet sometime to chat about this aspect with me?

2023-03-07 17:33 UTC, brindakv commented
>  Would you be able to meet sometime to chat about this aspect with me?

Sure. We can meet after the backend devs meeting today.

2023-03-07 17:38 UTC, brindakv commented
> Thanks for the review @brindakv. I'll be honest that I don't fully grasp how the subcategory nesting works...I had just copied the two `additional_properties` categories from `rcsb_polymer_entity_features.dic` to add the same in for `annotations`, but could easily have missed something else I needed to do. 

Defining nested categories and subcategories depends upon what we want the schema to be. Since mmCIF does not allow nesting, it has to be managed outside the dictionary.

2023-03-07 21:04 UTC, piehld commented on json_schema_definitions/json-full-db-pdbx_core-col-pdbx_core_polymer_entity.json
> +                        "name": "CARD AMR Detection"
@valasatava Is using this name OK? It seems to fit in with the other annotation types like this, e.g.,: https://github.com/rcsb/py-rcsb_exdb_assets/blob/dev-card-RO-3780/dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic#L125-L128

Otherwise, I can change it to just "CARD" as originally suggested in the jira ticket.

2023-03-07 21:07 UTC, piehld commented
Hi @valasatava and @brindakv, I've made the requested adjustments to the dictionaries and regenerated the schema files. Can you please have another look at the new versions? Thank you!

2023-03-07 23:50 UTC, brindakv approved these changes
Thanks @piehld. Looks good.

2023-03-08 00:00 UTC, valasatava approved these changes
Thank you, @piehld!

2023-03-08 00:02 UTC, valasatava commented on json_schema_definitions/json-full-db-pdbx_core-col-pdbx_core_polymer_entity.json
> +                        "name": "CARD AMR Detection"
@piehld it should be The Comprehensive Antibiotic Resistance Database and CARD

2023-03-08 01:15 UTC, piehld commented on json_schema_definitions/json-full-db-pdbx_core-col-pdbx_core_polymer_entity.json
> +                        "name": "CARD AMR Detection"
@valasatava OK, so you want it to be this?:
```
"value": "CARD",
"detail": "Comprehensive Antibiotic Resistance Database",
"name": "CARD"
```
As Brinda pointed out, the "name" field is assigned based on the value of `.rcsb_detail_brief`, so using just "CARD" will be somewhat different compared to the [other annotation types](https://github.com/rcsb/py-rcsb_exdb_assets/blob/dev-card-RO-3780/dictionary_files/extensions/annotations/rcsb_polymer_entity_annotations.dic#L125-L128). 

E.g., GO annotations have the following:
```
"value": "GO",
"detail": "Gene Ontology",
"name": "Gene Ontology"
```

Either way is OK with me, but I just want to make sure I point this out. Please let me know if you want me to continue with the original proposed plan.

2023-03-08 21:58 UTC, valasatava commented on json_schema_definitions/json-full-db-pdbx_core-col-pdbx_core_polymer_entity.json
> +                        "name": "CARD AMR Detection"
@piehld, looks like `name` is used by the UI to build the display name for attributes in the Adv.Search menu. I'd keep it as CARD, Comprehensive Antibiotic Resistance Database is too long for the menu

2023-03-09 14:07 UTC, piehld commented on json_schema_definitions/json-full-db-pdbx_core-col-pdbx_core_polymer_entity.json
> +                        "name": "CARD AMR Detection"
@valasatava OK sounds good, thanks. I've just updated accordingly.

2023-03-14 18:44 UTC, merged